language: node_js
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    secure: Az/e3D9VK+K8qwyjMjYc1IrO7FP5qKNO9vNxjxGwaBND/1FyRLgt8aH8lebgfioGQqWxZ/IW1kl3QWRThXBDfi02EQcZkBBAXVaEnBsMb6z0eroKxZw6uJly4r0NwWRN2h7IuPLPcjiveFGxP/qq1SSOgm4BX41caDMcqEdQ+gFLUlFb4VAwgfF3Jj+K/Xf5e7CwX7jsliEKN/aq+x0X+I32+did9x3gA3kO14OPioNr8j+hpYceCZZQpoMtqxdL1xUAHJiB0igcadQIBhdxD2qudeQQKFzkOD3fhQv6A69aF3Udbz7jJ62y6pZPMPmfP0kBpW569jFEbyCMnxfwd9c+7LxqJ3UlIIisg4lsg9NSTks1CJvNvB5BsSqmKbs6mc/VlpcbQjMFqkD2Xlt9FwjjmFZa1Ri/sUgPBAgz3yiibtnkXZ7wSPdbzkf9h/Qs9iODHfbXejuLDFp1GCjp5aq+OFs94iPaIss81eP4A5gq4y/vISe3YFvCTxy/W60hVUFZ34U+kIwv22XF+axS5R5K6fQQ1fL928ueybvN0/5F6kwxUsQeaahg8uSbIcGORVaCwcuNa3XKAinzY9dcgXtMwOvDG9XdokEdUJckUCY85dvnWhzYlQFPhj+ODECDoJtN9uG8Ljl6Y9PZiJ898jZpQ1EHsEK6oAtRWwqekF4=
