language: node_js
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      - secure: jS+/otRSGEo90p7/GlIzRCXCW2M5r5lvx5iBScjoqEjGethHmQfV29qMu/lGHyb4e/A4nZv5q5KD9pFQzSkQt+ddxmjep7uFWCjiWXDiODSEGZEUpRMm1cvMEEDdfOfJAb4j2hKDJyWII0L6WRbbtmjC7RUHfUSvJGGaesp2PrMCk0y7pLpL8l8pMUGwKwTab9buMtAn70qIOwTcSA0ygS522XzMjnEI4a4mPY3eqrpVa5nhrQz6Isa3HK9Gd4L9yTrTOg/1N7v8/aHVscDhUeiFMXI3xZa7Zb3lwI9GBoig1xiABT+zrvKsYj03TVVs7O8ChTFTzNM0WtgYo+Pm05MROR6gWrGxXna1T26w7M3PYyWMAp7KDS6OumTiJu3q/NE67z7XfZALxBAnwb7iBwe9hei+qZYyIGL25SFFks5NKKsip/dr5HjOBNncIheSQZQmWZOzTcB/JSeJyKxH2AZpjSWBsKNJmtKe684tVcnDmfOeFNsfRjeNWMTPHwYRKDA0PArw81DA9AKYPfoomH0e27e2mBhu0J1gzm5PltOsC0zpS6KTFzYx/u1+BqK9mFgKdDSYu8Hr0czNJia+lGMKFlT9nRMs+G8EiW947DPCbOwWtMP70dbm4PsQgpAVAsd26ugNNvUBapcE+EnJEZp0UnSCI63AsTW0ouofmVY=
